name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make all
      run: make all
    - name: make clean
      run: make clean
